export default {
  login: "dariusz75",
  id: 12503580,
  node_id: "MDQ6VXNlcjEyNTAzNTgw",
  avatar_url: "https://avatars.githubusercontent.com/u/12503580?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/dariusz75",
  html_url: "https://github.com/dariusz75",
  followers_url: "https://api.github.com/users/dariusz75/followers",
  following_url: "https://api.github.com/users/dariusz75/following{/other_user}",
  gists_url: "https://api.github.com/users/dariusz75/gists{/gist_id}",
  starred_url: "https://api.github.com/users/dariusz75/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dariusz75/subscriptions",
  organizations_url: "https://api.github.com/users/dariusz75/orgs",
  repos_url: "https://api.github.com/users/dariusz75/repos",
  events_url: "https://api.github.com/users/dariusz75/events{/privacy}",
  received_events_url: "https://api.github.com/users/dariusz75/received_events",
  type: "User",
  site_admin: false,
  name: "Dariusz Franczak",
  company: null,
  blog: "https://www.linkedin.com/in/dariusz-franczak-52251753/",
  location: "London",
  email: null,
  hireable: null,
  bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  twitter_username: null,
  public_repos: 128,
  public_gists: 0,
  followers: 3,
  following: 3,
  created_at: "2015-05-18T22:23:56Z",
  updated_at: "2022-11-13T14:53:37Z"
  };
